services:
  - type: web
    name: mp3-downloader-trimmer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      chmod 644 /etc/secrets/youtube.com_cookies.txt
      cat /etc/secrets/youtube.com_cookies.txt > /tmp/youtube.com_cookies.txt
      chmod 644 /tmp/youtube.com_cookies.txt
    startCommand: gunicorn -c gunicorn_config.py api.index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: MAX_THREADS
        value: 2
      - key: WEB_CONCURRENCY
        value: 1
    plan: free